-- ----------------------------
-- Table structure for SYS_USER
-- ----------------------------
DROP TABLE if exists "SYS_USER";
CREATE TABLE "SYS_USER" (
"ID" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
"USERNAME" varchar(60),
"PASSWORD" varchar(50),
"EMAIL" varchar(50),
"MAIN_ROLE_ID" int
);

COMMENT ON COLUMN "SYS_USER"."MAIN_ROLE_ID" IS '主要角色ID';

-- ----------------------------
-- Indexes structure for table SYS_USER
-- ----------------------------
--CREATE SEQUENCE  "SEQ_SYS_USER";
-- ----------------------------
-- Triggers structure for table SYS_USER
-- ----------------------------
--CREATE TRIGGER "TG_SYS_USER" BEFORE INSERT ON "SYS_USER" REFERENCING NEW AS NEWROW FOR EACH ROW
--BEGIN ATOMIC SELECT SEQ_SYS_USER.NEXTVAL INTO NEWROW.ID FROM DUAL; END;

